# -*- coding: utf-8 -*-
"""Vaccum cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPfVjHLsDDFukzn2v5E7ojGee9sM--IY
"""

import random

# Student Information
print("Name: Chitra Shree K S")
print("USN: 1WA24CS100")
print()

# Environment Constants
A = 'A'
B = 'B'
Clean = 'Clean'
Dirty = 'Dirty'

# Actions
MoveRight = 'MoveRight'
MoveLeft = 'MoveLeft'
Suck = 'Suck'
NoOp = 'NoOp'

# Agent function table
agent_table = {
    (Clean, A): MoveRight,
    (Clean, B): MoveLeft,
    (Dirty, A): Suck,
    (Dirty, B): Suck,
}

# Vacuum cleaner class
class VacuumCleaner:
    def __init__(self, location=A, status=Clean):
        self.location = location
        self.status = status
        # Keep track of both rooms' states to simulate a realistic environment
        self.env_status = {A: Clean, B: Clean}
        self.env_status[location] = status

    def percept(self):
        # Update current status based on the environment state of the current location
        self.status = self.env_status[self.location]
        return self.status

    def act(self, action):
        if action == MoveRight:
            self.location = B
        elif action == MoveLeft:
            self.location = A
        elif action == Suck:
            self.env_status[self.location] = Clean
            self.status = Clean

    def inject_dirt_randomly(self):
        # 50% chance to make Room A dirty, 50% chance for Room B
        if random.random() < 0.5:
            self.env_status[A] = Dirty
            print("--- [Env Notice]: Room A just got DIRTY! ---")
        if random.random() < 0.5:
            self.env_status[B] = Dirty
            print("--- [Env Notice]: Room B just got DIRTY! ---")

# Table-driven agent function
def table_driven_agent(percept):
    return agent_table.get(percept, NoOp)

# Main simulation loop
if __name__ == "__main__":
    # Initializing vacuum in Location A with a 'Clean' status
    vacuum = VacuumCleaner(location=A, status=Clean)

    for i in range(8):  # Increased to 8 steps to see more interactions
        print(f"--- Step {i+1} ---")

        # Randomly inject dirt into the environment before the agent senses it
        vacuum.inject_dirt_randomly()

        current_percept = vacuum.percept()
        action = table_driven_agent((current_percept, vacuum.location))

        print(f"Percept sensed: {(current_percept, vacuum.location)} -> Action taken: {action}")

        if action != NoOp:
            vacuum.act(action)

        print(f"Current State -> Location: {vacuum.location}, Status: {vacuum.status}")
        print(f"Full Env Map  -> Room A: {vacuum.env_status[A]}, Room B: {vacuum.env_status[B]}\n")